### ISSUE TITLE
ANSI Bright Black Against Integrated Terminal Background

### ISSUE THREAD

**Issue by spidercam** [tinkertrain/panda-syntax-vscode#10]
The ansiBrightBlack color in the integrated terminal is too dark against the background color:
![original](https://user-images.githubusercontent.com/113851/29882052-cd4d226e-8d60-11e7-8d72-84ddf326c1ae.jpeg)

Recommendation is to update the ansiBrightBlack color to a dark gray. Something like #696969. It constrasts better with the background:

![recommended](https://user-images.githubusercontent.com/113851/29882105-ecdc894e-8d60-11e7-95d3-8aaca531e7d0.jpeg)

**Comment by DHedgecock** [comment]
This will be fixed by #11
