### ISSUE TITLE
Any plans to support the Operator Mono font (italics) in VSCode?

### ISSUE THREAD

**Issue by mo-solnet** [tinkertrain/panda-syntax-vscode#13]
## Summary

I love the Panda theme but it does not seem to fully support the Operator Mono font in VSCode.

I've taken 3 screenshots for different themes to show the differences between them and Panda.
As you can see below, `this` and `console` are not in italics.
Also, the attributes in react components are not in italics either.

### One Dark
`comments` and `this` are rendered correctly but not `console`

![one dark](https://user-images.githubusercontent.com/30223210/30886145-86259f42-a372-11e7-8fc7-f0065ac90c34.png)

### Dracula
`this` and `console` are rendered correctly but not `comments`
![dracula](https://user-images.githubusercontent.com/30223210/30886149-8d24efd2-a372-11e7-9c5c-78307421b583.png)

### Panda
`comments` are rendered correctly but not `this` nor `console`
![panda](https://user-images.githubusercontent.com/30223210/30886152-8fbe6bce-a372-11e7-993c-f810ed56a452.png)

Language: JavaScript React

Raw File Contents:
```
            // clear timer for user account
            if (this.timer) {
                clearInterval(this.timer)
            }
            console.log('tada')
```

My settings.json

```
"editor.fontLigatures": true,
"editor.fontFamily": "Operator Mono, Monaco, Menlo, 'Courier New', monospace",
"editor.renderWhitespace": "boundary",
"editor.autoIndent": true,
```

**Releasing a version of Panda that supports Mono Operator would be awesome 💯 👍**

**Comment by siamak** [comment]
@mo-solnet Thanks for Using Panda. In new version (soon) we fix them.

**Comment by hegelstad** [comment]
What is the timeline? days, weeks or months? Really want this feature.

**Comment by siamak** [comment]
@hegelstad Now you can update Panda to version `1.2.0`

**Comment by hegelstad** [comment]
@siamak I am not able to get version 1.2.0 when installing from extensions, same when installing via the extension marketplace (where it says the newest version is 1.2.0).

**Comment by hegelstad** [comment]
Also, please add italics for import
