### ISSUE TITLE
High contract areas

### ISSUE THREAD

**Issue by wprater** [tinkertrain/panda-syntax-vscode#14]
These areas feel a bit too high contrast and make it hard to read text when they are used as a background color.

Perhaps a darker font when the status bar is in debug mode?
![image](https://user-images.githubusercontent.com/10452/31155980-e5748b7c-a866-11e7-8bcf-bad325e21dd2.png)

Again darker fonts may improve legibility here. 
![image](https://user-images.githubusercontent.com/10452/31155971-dab08600-a866-11e7-871a-83d5ce7c066a.png)

**Comment by siamak** [comment]
@wprater In new version (soon) we fix this issue.
