### ISSUE TITLE
Change to default error line

### ISSUE THREAD

**Issue by vebjorni** [tinkertrain/panda-syntax-vscode#15]
Hi.

How can I change so that I get the normal error line instead of the double line when linting?

Thanks!

**Comment by vebjorni** [comment]
Remove editorError.border line in Panda.json to just get the squggly line.

**Comment by lselden** [comment]
For anyone looking for how to make this change without editing the extension:
* Ctrl+Shift+P to open command palette, choose "Preferences: Open Settings (JSON)"
* Add the following entry (will make the double bars transparent:
```json
"workbench.colorCustomizations": {
	"[Panda Syntax]": {
		"editorError.border": "#FF4B8200",
	}
}
```
