### ISSUE TITLE
Syntax highlight in jsx

### ISSUE THREAD

**Issue by irfanabliz** [tinkertrain/panda-syntax-vscode#17]
first of all, I personally really like this theme, but the only problem I'm having is that in react javascript, I want to get html to be the same highlight as in html, that would be really really cool, because the red colour for html tags are super awesome.

here is the screenshot of what i'm having now.

<img width="337" alt="screen shot 2018-01-29 at 5 23 32 pm" src="https://user-images.githubusercontent.com/17282448/35537795-95046922-0519-11e8-8128-de0df7001b12.png">

turn that html tags in jsx into this

<img width="891" alt="screen shot 2018-01-29 at 5 27 49 pm" src="https://user-images.githubusercontent.com/17282448/35537877-d3bd377a-0519-11e8-995f-bc0340c41f9d.png">

**Comment by irfanabliz** [comment]
I currently still using atom, so I think I will stay with atom cuz its way more prettier than vscode. Thanks for this awesome theme anyway!

**Comment by alvaromb** [comment]
This is the main issue I have right now with this theme. I cannot use it if it doesn't correctly highlight JSX tags.
