### ISSUE TITLE
Broken in latest VSCode February release

### ISSUE THREAD

**Issue by nfantone** [tinkertrain/panda-syntax-vscode#28]
## Summary

Right after upgrading to latest `1.43.0` Visual Studio (February 2020 release), JavasScript functions and properties have lost their original colors.

- Properties in objects are now the same colors as functions (used to white, are now blue), which makes them hard to distinguish and read.
- Global constructors such as `Number` or `String`, used to be yellow-ish - they are now white.

![image](https://user-images.githubusercontent.com/476069/76312094-34faf800-62ca-11ea-9bf5-4b81048703a7.png)

- Exported members used to be white, are now blue.

![image](https://user-images.githubusercontent.com/476069/76312213-7095c200-62ca-11ea-9cd3-fac95f400c4b.png)

- `require` statements are now white (used to be blue).

![image](https://user-images.githubusercontent.com/476069/76312287-9d49d980-62ca-11ea-8dfb-a4ff676c13ba.png)

**Language**: JavaScript
**Raw File Contents**:

```js
/**
 * @function
 */
const toUserFormField = applySpec({
  id: prop('id'),
  name: prop('name'),
  icon: prop('icon'),
  type: prop('type'),
  placeholder: prop('placeholder'),
  required: compose(boolify, prop('required')),
  unique: compose(boolify, prop('unique')),
  multiple: compose(boolify, prop('multiple')),
  values: compose(sortBy(ascend(prop('ordinal')), map(toAttributeValue), prop('values'))),
  attribute: prop('attribute'),
  colGroup: prop('col_group'),
  helpText: prop('help_text'),
  validations: compose(parseValidationRules, propOr('', 'validation_rules')),
  ordinal: compose(Number, prop('ordinal'))
});
```

**Comment by nfantone** [comment]
Related to https://github.com/microsoft/vscode/issues/92308.

**Comment by Fasani** [comment]
This issue can be closed. It would appear https://github.com/microsoft/vscode/issues/92308 is now closed and I can confirm the theme seems to work as expected today, see screenshot.

<img width="361" alt="Screenshot 2020-05-27 at 10 34 29" src="https://user-images.githubusercontent.com/448410/82996911-f7bf2000-a005-11ea-9645-421578293ed3.png">

**Comment by nfantone** [comment]
Agreed. Closing.
