### ISSUE TITLE
Support PHP lang

### ISSUE THREAD

**Issue by siamak** [tinkertrain/panda-syntax-vscode#3]
Hello @tinkertrain. I hope you're great. In VSCode port of Panda it isn't good supporting PHP Language. Can fixed it?

**Comment by tinkertrain** [comment]
Hi @siamak, all I did was porting the sublime theme using the visual code yo generator. I don't know much about coding the themes themselves...

**Comment by siamak** [comment]
@tinkertrain Now I fixed PHP colors on Sublime Text port. Please update VSCode port as soon as. Thanks :)
https://github.com/siamak/panda-syntax-sublime/blob/master/Panda/panda-syntax.tmTheme
