### ISSUE TITLE
What's going on with the project site? Domain expired?

### ISSUE THREAD

**Issue by jrolfs** [tinkertrain/panda-syntax-vscode#37]
↓ http://panda.siamak.work/ ↓

<img width="1532" alt="project-site-1" src="https://user-images.githubusercontent.com/288160/114076033-0b105e00-985b-11eb-948e-6233cdf56d6d.png">

↓ http`s`://panda.siamak.work/ ↓

<img width="1532" alt="project-site-2" src="https://user-images.githubusercontent.com/288160/114076222-46ab2800-985b-11eb-8f34-9273fcecc521.png">

**Comment by siamak** [comment]
@jrolfs http://panda.siamak.me/

**Comment by jrolfs** [comment]
Yeah, I meant to mention that I found the proper URL with some digging but you might want to update the URL in the repository settings and readme.
