### ISSUE TITLE
Domain siamak.work is now for sale

### ISSUE THREAD

**Issue by psydvl** [tinkertrain/panda-syntax-vscode#40]
As domain `siamak.work` is now for sale, should it (as `panda.siamak.work`) be removed from `README` and repository details on right side?

**Comment by maximilienGilet** [comment]
It now redirects to some porn so yeah please remove it 😅

**Comment by siamak** [comment]
Oh Sorry for delay, It's working on https://panda.siamak.me/

**Comment by psydvl** [comment]
Why closed? 
README and project information still having old site...
