### ISSUE TITLE
some bugs with latest update

### ISSUE THREAD

**Issue by Talor-A** [tinkertrain/panda-syntax-vscode#5]
hello, thank you for bringing full theme support to panda! it's my favorite theme for VSCode. However, there seems to be a lot that has changed and the syntax highlighting seems less organized and has a few bugs. I'm a little confused by the YAML theme files, but maybe I could work on a PR. Here's what I've noticed.

1. react JSX components no longer have colored names in markup, the red is gone now and it (to me) is less legible (screenshot is of previous version)
![screenshot from 2017-08-24 15-30-23](https://user-images.githubusercontent.com/11509865/29691814-94b189f0-88e1-11e7-95c2-49099f254536.png)

2. these weird error underlines
![screenshot from 2017-08-24 15-22-10](https://user-images.githubusercontent.com/11509865/29691854-d09d3018-88e1-11e7-8ba4-658e8794da6c.png)

3. JS class methods are not properly colored (they are white now, not blue)
![screenshot from 2017-08-24 15-38-28](https://user-images.githubusercontent.com/11509865/29691945-6235297c-88e2-11e7-9343-5f03a2f0630d.png)

4. class decorators are no longer colored (see above screenshot)

5. `import..from`, and  `export` keywords are no longer colored (see above again)

Again I would be happy to help with a PR if you could show me where to get started. thanks.

**Comment by siamak** [comment]
@Talor-A I guess your packages for syntax highlight have issue. but I will check this issue soon. Cheers.

**Comment by DHedgecock** [comment]
Hello @Talor-A , the red squiggly lines are warnings from your linter that your syntax is not valid, which is breaking the syntax token generation done by the grammar.

If you fix the syntax errors it should resolve your problems, something like:
`import  from '......'` (invalid import syntax)
=> `import TensorFlow from '.......'`

`export default  extends Component {` (invalid class definition)
=> `export default class Demo extends Component {`

You likely have other syntax errors in the decorator file, but I can't tell. Feel free to paste the entire file if you'd like help. Highlighter should look like:
<img width="717" alt="screen shot 2017-08-25 at 7 36 54 am" src="https://user-images.githubusercontent.com/8461733/29718631-45cc4a14-8968-11e7-9cf6-7db1d3614afd.png">

**Comment by DHedgecock** [comment]
If this is not resolved please provide raw contents of file so we can investigate. Thanks

**Comment by Talor-A** [comment]
@DHedgecock I provided those errors just to demonstrate the strange multiple outlines that are appearing. Here's a screenshot + raw text of an error-free file. you can see that the unused imports are causing the linter to complain and show the strangle multiple underlines, but removing those imports (so there are no linting problems) doesn't fix the incorrect syntax highlighting, in case you were curious. If there's any other info you want me to provide I'm happy to help.

![screenshot from 2017-08-28 13-42-12](https://user-images.githubusercontent.com/11509865/29792968-05b3f896-8bf7-11e7-9b04-4c03c7e1a1d2.png)


```
import React, { Component } from 'react'
import { View, ScrollView } from 'react-native'
import { connect } from 'react-redux'
import { Text, Icon, Button } from 'native-base'
import { getUsers } from '../../redux/users'
import { logout } from '../../redux/user'
import Contact from './contact-list-item'

const mapStateToProps = ({ users }) => ({
  users: Object.values(users)
})
const mapDispatchToProps = dispatch => ({
  getUsers: () => dispatch(getUsers())
})

@connect(mapStateToProps, mapDispatchToProps)
export default class Contacts extends Component {
  componentDidMount () {
    this.props.getUsers()
  }
  render () {
    return (
      <ScrollView>
        {this.props.users.length
          ? this.props.users.map(user => <Contact user={user} key={user.uid} />)
          : <View
            style={{
              flex: 1,
              padding: 16,
              alignSelf: 'center',
              justifyContent: 'center'
            }}>
            <Text style={{ opacity: 0.3, fontSize: 24 }}>
                You Have No Contacts :(
              </Text>
            <Text>
              {JSON.stringify(this.props, null, 2)}
            </Text>
          </View>}
      </ScrollView>
    )
  }
}

```

**Comment by DHedgecock** [comment]
Thanks for the raw file, it looks like you're using the Sublime Babel extension for your grammar. With all grammar/theme combinations some work together well and some don't. Panda works best with the VSCode grammars and has varying degrees of success with other grammar extensions. Here is a note from the Babel Sublime extension:
![screen shot 2017-08-28 at 3 42 04 pm](https://user-images.githubusercontent.com/8461733/29796725-a94dd638-8c07-11e7-8f5e-387e3e996f94.png)

I tried out a few different extensions and Babel Sublime paired with Panda the least well ☹️

For what it's worth, the VSCode languages have come a looooong way. I use them for all of my Typescript+React dev and the highlighting is solid.

**Comment by Talor-A** [comment]
ah thanks! the default grammar looks great. also happy to need one less extension in VS Code...

**Comment by DHedgecock** [comment]
![Rad](http://gph.is/1J91gGV)
