### ISSUE TITLE
Color selector text like color property text

### ISSUE THREAD

**Issue by KytoSai** [tinkertrain/panda-syntax-vscode#6]
I like new update . But in .scss file , color selector text like color property text . It not good :( 
http://prntscr.com/gcqu7d

**Comment by siamak** [comment]
@KytoSai We will fix this issue ;)

**Comment by siamak** [comment]
@KytoSai Update you panda theme. Fixed this issue.

**Comment by KytoSai** [comment]
Thank you so much 👍  !!!!
