### ISSUE TITLE
there‘s some ’font color too dim in vs code terminal such as npm i -g

### ISSUE THREAD

**Issue by bestvow** [tinkertrain/panda-syntax-vscode#8]
![snipaste_2017-08-30_09-54-47](https://user-images.githubusercontent.com/24888709/29852019-3a61a498-8d6a-11e7-9024-fee3a30bc4d6.png)

wish you can understand my worst english

**Comment by siamak** [comment]
@DHedgecock Do you have solution for this issue?

**Comment by DHedgecock** [comment]
This will be fixed by #11
